name: azure-gpt-rag
infra:
  provider: bicep
  path: infra
  module: main
hooks:
  predeploy:
    posix:
      shell: sh
      run: scripts/hooks/preDeploy.sh
      interactive: true
    windows:
      shell: pwsh
      run: scripts/hooks/preDeploy.ps1
      interactive: true
  preprovision:
    posix:
      run: scripts/hooks/preProvision.sh
      interactive: true
    windows:
      run: scripts/hooks/preProvision.ps1
      interactive: true      
services:
  dataingest:
    host: containerapp
    image: ${AZURE_CONTAINER_REGISTRY_NAME}.azurecr.io/azure-gpt-rag/dataingest-build:${TAG}
